version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Running Maven tests"
      - mvn test -DsuiteXmlFile=suite/Functional.xml -DtestFailureIgnore=false

post_build:
  commands:
    - export DATE_TIME=$(date +%F/%H-%M-%S)
    - export FILE_NAME="Functional_Report_default_${DATE_TIME//\//_}.html"
    - export S3_FOLDER="2025-06-02/11-17-21"  # Or generate dynamically like: $(date +%F/%H-%M-%S)
    - export S3_BUCKET="dcmplaywright-report"
    - export REGION="us-east-1"

    # Upload report
    - aws s3 cp test-output/Reports/$FILE_NAME s3://$S3_BUCKET/$S3_FOLDER/$FILE_NAME

    # Construct static S3 URL (make sure your bucket allows public read OR restrict via CloudFront)
    - export REPORT_URL="https://${S3_BUCKET}.s3.${REGION}.amazonaws.com/${S3_FOLDER}/${FILE_NAME}"

    # Determine Maven result
    - |
      if [ $? -eq 0 ]; then
        STATUS="✅ *Test Success*"
      else
        STATUS="❌ *Test Failed*"
      fi

    # Send to Google Chat
    - |
      curl -X POST -H "Content-Type: application/json" \
        -d "{
              'text': '${STATUS}\n\n[Click here to view the report](${REPORT_URL})'
            }" \
        'https://chat.googleapis.com/v1/spaces/AAAA0q_7a84/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=2sgTj39vsGjHblKJrS_pAKTiHPxXi08Z-LG0lHmma4I'

