version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Running Maven tests"
      - mvn test -DsuiteXmlFile=suite/Functional.xml -DtestFailureIgnore=false

  post_build:
    commands:
      - echo "Uploading test reports to S3..."
      - export DATE_TIME=$(date +%F/%H-%M-%S)
      - echo "Uploading to s3://dcmplaywright-report/$DATE_TIME/"
      - aws s3 cp test-output/Reports/ s3://dcmplaywright-report/$DATE_TIME/ --recursive
