version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
build:
  commands:
    - java -version
    - javac -version
    - mvn test -DsuiteXmlFile=suite/Functional.xml -DtestFailureIgnore=false
