version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - |
        apt-get install -y \
        libgtk-4-1 libgraphene-1.0-0 libwoff1 libvpx9 libevent-2.1-7 \
        libopus0 libgstreamer1.0-0 libgstreamer-plugins-base1.0-0 \
        libflite1 libavif16 libharfbuzz-icu0 libsecret-1-0 \
        libhyphen0 libmanette-0.2-0 libgles2 libx264-dev
      - pip install awscli

  build:
    commands:
      - echo "Running Maven tests"
      - cd dmstest/prj/UITest/Playwright/Automation
      - mvn test -DsuiteXmlFile=suite/Functional.xml -DtestFailureIgnore=false | tee mvn-output.txt
      - grep -i "Error:  Tests run:" mvn-output.txt || true

  post_build:
    commands:
      - echo "Build complete"
      - echo "Uploading test reports to S3"
      - |
        BUCKET_NAME="dcmplaywright-report"
        TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
        S3_REPORT_PATH="test-reports/${CODEBUILD_RESOLVED_SOURCE_VERSION}/$TIMESTAMP"
        REPORT_FOLDER="dmstest/prj/UITest/Playwright/Automation/test-output/Reports"
        if [ -d "$REPORT_FOLDER" ]; then
          aws s3 cp "$REPORT_FOLDER" "s3://$BUCKET_NAME/$S3_REPORT_PATH/" --recursive
        else
          echo "Report folder not found: $REPORT_FOLDER"
        fi
      - echo "Sending message to Google Chat"
      - |
        if grep -q "BUILD SUCCESS" mvn-output.txt; then
          STATUS="✅ Maven tests passed"
        else
          STATUS="❌ Maven tests failed"
        fi
        REPORT_LINK="https://${BUCKET_NAME}.s3.amazonaws.com/${S3_REPORT_PATH}/"
        MESSAGE="{\"text\": \"$STATUS in *${CODEBUILD_SOURCE_REPO_URL}* on branch *${CODEBUILD_SOURCE_VERSION}*.\n👉 [View Report]($REPORT_LINK)\"}"
        curl -X POST -H 'Content-Type: application/json' -d "$MESSAGE" \
          "https://chat.googleapis.com/v1/spaces/AAQAqt13dik/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Fekd0ej4-FE4jAO4CQFTdW0jM47BMywaNvMKyrEwWaE"
