version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # or your Java version
  build:
    commands:
      - cd dmstest/prj/UITest/Playwright/Automation
      - mvn test -DsuiteXmlFile=suite/Functional.xml -DtestFailureIgnore=false
